import type { Metadata } from "next";
import "./globals.css";
import Providers from "@/app/providers";
import Header from "@/components/header";
import { SessionProvider } from "next-auth/react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="container mx-auto px-4 max-w-6xl">
          <SessionProvider>
            <Header />
            <Providers>{children}</Providers>
          </SessionProvider>
        </div>
      </body>
    </html>
  );
}
